name: Go Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Verify dependencies
        run: go mod tidy && go mod verify

      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -v -o raminfo ./ 

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -v -o raminfo.exe ./

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git

      - name: Create or update 'latest' release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if release exists
          if ! gh release view latest &>/dev/null; then
            echo "Release 'latest' does not exist. Creating..."
            gh release create latest --title "Latest Release" --notes "Automatically updated release" raminfo raminfo.exe
          else
            echo "Release 'latest' exists. Updating assets..."
            gh release upload latest raminfo raminfo.exe --clobber
          fi
